

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using App.Model;


namespace Win.App.Server.DataSource
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class QuizBeeEntities : DbContext
{
    public QuizBeeEntities()
        : base("name=QuizBeeEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ContestantScore> ContestantScores { get; set; }

    public virtual DbSet<QuizL1> QuizL1 { get; set; }

    public virtual DbSet<QuizL2> QuizL2 { get; set; }

    public virtual DbSet<QuizL3> QuizL3 { get; set; }

    public virtual DbSet<Clincher> Clinchers { get; set; }

    public virtual DbSet<GQuiz> GQuizs { get; set; }

    public virtual DbSet<GContestantScore> GContestantScores { get; set; }

    public virtual DbSet<AdminAccount> AdminAccounts { get; set; }

    public virtual DbSet<TallySheet> TallySheets { get; set; }

    public virtual DbSet<GTallySheet> GTallySheet { get; set; }

}

}

