
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace App.Model
{

using System;
    using System.Collections.Generic;
    
public partial class GTallySheet
{

    public int Id { get; set; }

    public string ContestantName { get; set; }

    public int QuestionNumber { get; set; }

    public string Answer { get; set; }

}

}
