
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace App.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Participant
{

    public int Id { get; set; }

    public string TeamName { get; set; }

    public string Participant1 { get; set; }

    public string Participant2 { get; set; }

    public string Participant3 { get; set; }

    public string Participant4 { get; set; }

    public string Participant5 { get; set; }

}

}
